/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CurpResponse } from "./components/gov-form/gov-form";
export namespace Components {
    interface GovForm {
        "apikey": string;
    }
}
declare global {
    interface HTMLGovFormElement extends Components.GovForm, HTMLStencilElement {
    }
    var HTMLGovFormElement: {
        prototype: HTMLGovFormElement;
        new (): HTMLGovFormElement;
    };
    interface HTMLElementTagNameMap {
        "gov-form": HTMLGovFormElement;
    }
}
declare namespace LocalJSX {
    interface GovForm {
        "apikey"?: string;
        "onCompleted"?: (event: CustomEvent<CurpResponse>) => void;
    }
    interface IntrinsicElements {
        "gov-form": GovForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gov-form": LocalJSX.GovForm & JSXBase.HTMLAttributes<HTMLGovFormElement>;
        }
    }
}
