import { Database } from '../../database/database';
import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';
import algoliasearch from 'algoliasearch';

const client = algoliasearch(functions.config().algolia_partners.appid, functions.config().algolia_partners.apikey);
const index = client.initIndex(functions.config().algolia_partners.index);

export class Driver {
  private database = new Database();

  async localizate(_geoloc: { lat: string; lng: string }) {
    const availableDrivers = await index.search('', {
      aroundRadius: 12000,
      facetFilters: ['isAnActivePartner:true'],
      aroundLatLng: `${_geoloc.lat}, ${_geoloc.lng}`,
    });
    const availableDriver = availableDrivers.hits[0] as any;
    if (availableDriver) {
      const notification = {
        title: `Nueva compra, ¿vamos hacer que pase?`,
        body: `👍 ¿Eres un hacedor de milagros?`,
      };
      const payload: admin.messaging.Message = {
        notification,
        webpush: {
          notification: {
            vibrate: [200, 100, 200],
            icon:
              'https://firebasestorage.googleapis.com/v0/b/arsus-production.appspot.com/o/logo-transparent.png?alt=media&token=485a5c1c-a436-41f7-b126-57c6e3ce75bb',
            actions: [
              {
                action: 'accept',
                title: '👍 ¿Eres un hacedor de milagros?',
              },
            ],
            openUrl: 'https://arsus.com.mx/home/partners',
            requireInteraction: true,
            badge:
              'https://firebasestorage.googleapis.com/v0/b/arsus-production.appspot.com/o/logo-transparent.png?alt=media&token=485a5c1c-a436-41f7-b126-57c6e3ce75bb',
          },
        },
        topic: `arsus-enterprise${availableDriver.uid}`,
      };
      this.database.collection(`users/${availableDriver.uid}/notificationsEnterprise`).storeAutogeneratedUID({
        img: availableDriver.driverPhotoURL,
        label: `Nueva compra a domicilio`,
        path: '/home/kitchen',
        time: new Date().toISOString(),
      });
      admin.messaging().send(payload);
      return {
        driverName: availableDriver.driverName,
        driverPhotoURL: availableDriver.driverPhotoURL,
        driverUID: availableDriver.uid,
        driverPhoneNumber: availableDriver.phoneNumber,
        driverVehicle: availableDriver.driverVehicle,
      };
    }
    return {
      driverName: 'Buscando repartidor',
      driverPhotoURL:
        'https://firebasestorage.googleapis.com/v0/b/arsus-production.appspot.com/o/articles%2FimgMobile-image-not-availaible.png?alt=media',
      driverUID: '',
      driverPhoneNumber: '+526461924594',
      driverVehicle: 'N/A',
    };
  }
}
